---
- hosts: all
  tasks:
  - name: setup directories
    file:
      path: "{{ item }}"
      state: directory
      recurse: no
      mode: 0750
    loop:
    - "~/src"
  - name: install packages
    apt:
      state: present
      force_apt_get: True
      name:
      - build-essential
      - curl
      - ddd
      - docker.io
      - firefox
      - fonts-powerline
      - git
      - git-email
      - git-extras
      - gnome-clocks
      - gnupg
      - golang-go
      - htop
      - jq
      - mutt
      - nodejs
      - pcscd
      - python3-gpg
      - python3-pip
      - qemu-system-x86
      - scdaemon
      - tmux
      - yubikey-manager
  - name: install python packages
    pip:
      name:
      - docker-compose
  - name: install snap packages
    snap:
      classic: yes
      name:
      - signal-desktop
      - bitwarden
      - spotify

  - name: install npm packages
    npm:
      name: quicktype
      global: yes

  - name: setup default editor
    alternatives:
      name: editor
      path: /usr/bin/nvim
