---
- hosts: all
  tasks:
  - name: setup directories
    file:
      path: "{{ item }}"
      state: directory
      recurse: no
      mode: 0750
    loop:
    - "~/src"
  - name: install packages
    apt:
      state: present
      force_apt_get: True
      name:
      - docker.io
      - curl
      - firefox
      - git
      - git-email
      - git-extras
      - htop
      - jq
      - mutt
      - tmux
      - fonts-powerline
      - yubikey-manager
      - gnupg
      - pcscd
      - scdaemon
      - python3-gpg
  - name: uninstall packages
    apt:
      state: absent
      name:
      - rustc
      - cargo
      - golang-go
  - name: install snap packages
    snap:
      classic: yes
      name:
      - signal-desktop
      - nvim
      - bitwarden
      - spotify
  - name: setup default editor
    alternatives:
      name: editor
      path: /usr/bin/nvim
