---
- hosts: all
  tasks:
  - name: install packages
    apt:
      state: present
      force_apt_get: True
      name:
      - ansible
      - docker.io
      - firefox
      - git
      - git-email
      - git-extras
      - htop
      - jq
      - mutt
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - openssh-server
      - tmux
      - vim
  - name: install snap packages
    snap:
      classic: yes
      name:
      - goland
      - remmina
      - signal-desktop
      - slack
      - spotify
  - name: setup default editor
    alternatives:
      name: editor
      path: /usr/bin/vim
  - name: disable clear-text passwords
    replace:
      path: /etc/ssh/sshd_config
      regexp: '^#PasswordAuthentication yes'
      replace: 'PasswordAuthentication no'
